### ISSUE TITLE
worklog-for-pdf-bug!

### ISSUE THREAD

**Issue by masayuki14** [masayuki14/rabbit#4]
https://github.com/rabbit-shocker/rabbit/issues/107
コマンドからPDF出力すると画像サイズがおかしくなるバグの原因を突き止める。
そもそもバグなのか、というところ。

**Comment by masayuki14** [comment]
`bin/` にコマンドがあるので `Rakefile` をみてどうやってコマンドが作られてるかを見てみよう。

**Comment by masayuki14** [comment]
いや、ちがう。バイナリのコマンドじゃないじゃないか！

**Comment by masayuki14** [comment]
```
#!/usr/bin/env ruby
require "rabbit/command/rabbit"
exit(Rabbit::Command::Rabbit.run(*ARGV))
```
でした。
よし潜ろう。

**Comment by masayuki14** [comment]
`rabbit/command/rabbit.rb` を見る。

**Comment by masayuki14** [comment]
ところでクローンしたリポジトリのコードで動くんだろうか。

```
%  ./bin/rabbit 'https://raw.githubusercontent.com/masayuki14/reserve-docs/master/slide/first-contact-oss-gate/slide.md'

/Users/xxx/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rabbit/command/rabbit (LoadError)
	from /Users/xxx/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bin/rabbit:20:in `<main>'
```
あかーん。

**Comment by masayuki14** [comment]
bundler だよ !!! :anguished:

```
%  bundle exec ./bin/rabbit 'https://raw.githubusercontent.com/masayuki14/reserve-docs/master/slide/first-contact-oss-gate/slide.md'
```

**Comment by masayuki14** [comment]
パースしてるのはここだよー。
https://github.com/rabbit-shocker/rabbit/blob/master/lib/rabbit/command/rabbit.rb#L320-L324

```ruby
          parser.on("-p", "--print",
                    _("Print and exit.")) do
            options.action = :print
          end

```

**Comment by masayuki14** [comment]
`options.action` に `:print` を代入している。
ここかなー。
https://github.com/rabbit-shocker/rabbit/blob/master/lib/rabbit/command/rabbit.rb#L57-L66

```ruby
        application.signal_connect("activate") do
          begin
            succeeded = catch do |abort_tag|
              @abort_tag = abort_tag
              __send__("do_#{@options.action}")
            end
          rescue
            @logger.error($!)
          end
        end
```

**Comment by masayuki14** [comment]
`__send__()` と `send()` の違いは？

> send が再定義された場合に備えて別名 __send__ も 用意されており、ライブラリではこちらを使うべきです。また __send__ は再定義すべきではありません。
by るびま

なるほど。

**Comment by masayuki14** [comment]
ということで `do_print` をgrepしよう。

```sh
% grep -rin 'do_print' lib
lib/rabbit/command/rabbit.rb:808:      def do_print
lib/rabbit/renderer/base.rb:88:          do_print(&block)
lib/rabbit/renderer/base.rb:265:      def do_print(&block)
```

**Comment by masayuki14** [comment]
https://github.com/rabbit-shocker/rabbit/blob/master/lib/rabbit/command/rabbit.rb#L809-L819

```ruby
      def do_print
        source = make_source
        renderer = Renderer.printable_renderer(@options.slides_per_page)
        canvas = make_canvas(renderer)
        setup_paper_size(canvas)
        setup_print_info(canvas)
        setup_3d_info(canvas)
        apply_theme_if_need(canvas)
        parse(canvas, source)
        canvas.print
        canvas.quit
        true
      rescue ::Rabbit::NoPrintSupportError
        @logger.error($!.message)
        false
      end
```
ここのどこかにあるということかな :stuck_out_tongue:

**Comment by masayuki14** [comment]
スライドから出力する部分と比較したいところだけど・・・:confused:
